---
title: "PediTools package notes"
author: "Joseph Chou"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## `charts_long.csv` to `lmsdata` to `sysdata.rda`

`charts_long.csv` columns:

* chart
* age
* age_units
* gender
* measure
* measure_units
* L, M, S

* `sysdata.rda` needs to be saved in the correct format for package use, inside the `R` code directory

```r
lmsdata <- read.csv(file = 'data-raw/charts_long.csv', stringsAsFactors = TRUE) # read from CSV file
usethis::use_data(lmsdata, internal = TRUE, overwrite = TRUE)                   # save dataframe into sys.data in proper format
```

## Generate table of available charts / measures

```r
lmsdata %>%
#  filter(chart != 'fenton_2013') %>%
  mutate(measure = paste0(measure, '(', measure_units,')')) %>%
  select(chart, age_units, measure) %>%
  unique() %>%
  group_by(chart, age_units) %>%
  summarise(measures = paste(sort(measure), collapse = ', ')) %>%
  arrange(chart)
```

### Generate table of charts / measures with age ranges

```r
lmsdata %>%
  group_by(chart, age_units) %>%
  summarise(
    min = min(age) %>% round(),
    max = max(age) %>% round(),
    measures = paste(unique(measure), collapse=', ')
  ) %>%
  ungroup() %>%
  transmute(
    chart = chart,
    range = paste0(min, '-', max),
    age_units,
    measures
  )
```

For `roxygen2` documentation:

```r
tabular <- function(df, ...) {
  stopifnot(is.data.frame(df))

  align <- function(x) if (is.numeric(x)) "r" else "l"
  col_align <- vapply(df, align, character(1))

  cols <- lapply(df, format, ...)
  contents <- do.call("paste",
    c(cols, list(sep = " \\tab ", collapse = "\\cr\n#'   ")))

  paste(
    "#' \\tabular{", paste(col_align, collapse = ""), "}{\n#'   ",
    paste0("\\strong{", names(df), "}", sep = "", collapse = " \\tab "), " \\cr\n#'   ",
    contents, "\n#' }\n", sep = "")
}

lmsdata %>%
#  filter(chart != 'fenton_2013') %>%
  mutate(measure = paste0(measure, '(', measure_units,')')) %>%
  select(chart, age_units, measure) %>%
  unique() %>%
  group_by(chart, age_units) %>%
  summarise(measures = paste(sort(measure), collapse = ', ')) %>%
  arrange(chart) %>%
  tabular() %>%
  cat()
```

## Rebuild documentation

```r
devtools::document() # rebuld documentation
```

## Building the package

```r
library(devtools)
# setwd("~/Desktop/R/peditools")
setwd("~/Dropbox (Partners HealthCare)/R/peditools")
setwd("..") # to build package, need to be in directory where package DIRECTORY is
install("peditools")
```

Create a `tar.gz` version of the package

* check where the tar.gz version of the package ends up

```r
build('peditools')
```

Inside of Terminal:

To build a .tar.gz file (a “tarball”) for sharing the package:

* `R CMD build myPackageName`

To install the package from its folder:

* `R CMD install myPackageName`

To check the package, perhaps before submitting to CRAN:

* `R CMD check myPackageName`


## PediTools package install on MacOS, from terminal

* `~/Dropbox\ \(Partners\ HealthCare\)/R/peditools/`

* `R CMD INSTALL /Users/jeanjoe/Dropbox/peditools_0.3.0.9000.tar.gz`

## PediTools package install on Windows

* `Start --> CMD`
* `"C:\R\R-3.5.2\bin\R.exe" CMD INSTALL H:peditools_0.1.2.tar.gz`

